pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
             label 'master'
      }
    }
    environment {
    DEPLOY_PROJECT = "jenkins-deploy"
    }

    stages {


        stage('Getting Started...'){
          steps {
             sh ' echo Hello, now will start your build and deployment.'
        }
    }

        stage('Starting Build and Deployment') {
          steps {
            sh '''
                 oc project $DEPLOY_PROJECT
                 oc new-app --name jenkins-build-app --code https://github.com/shkatara/sunny-do288-repo
               '''

          }
        } 

        stage('Prompt for Route.') {
          steps {
             input message: "Create a route ?"
             sh '''
                oc project $DEPLOY_PROJECT
                oc expose svc jenkins-build-app
                '''
          }
        }
       
 
        stage('All Done'){
          steps {
             sh ' echo Your Pipeline is finished executing. Access your application from the jenkins-build-app route in jenkins-deploy project.'
          }
       }

     }
} 
