pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
             label 'master'
      }
    }
    environment {
    DEPLOY_PROJECT = "jenkins-deploy"
    }

    stages {


        stage('Getting Started...'){
          steps {
             sh ' echo Hello, now will start your build and deployment.'
        }
    }

        stage('Starting Deployment') {
          steps {
            sh '''
                 oc project $DEPLOY_PROJECT
                 oc new-app --name from-jenkins --code https://github.com/shkatara/sunny-do288-repo
               '''

          }
        } 

        stage('Prompt for a route..') {
          steps {
             input message: "Create a route ?"
             sh '''
                oc project $DEPLOY_PROJECT
                oc expose svc from-jenkins
                '''
          }
        }
     }
} 
